version: "3"
services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=google_crawler_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
